site_name: reDIVE World
site_url: https://redive.world
site_description: Let's all DIVE again!
site_author: Yellow
repo_url: https://github.com/YellowberryHN/redive

theme:
  name: material
  navigation_depth: 3
  palette:
    primary: custom
    accent: custom
    scheme: slate
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.sections
    - navigation.expand
extra_css:
  - css/extra.css

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
  - offline
markdown_extensions:
    - callouts
    - attr_list
    - md_in_html

nav:
  - Home: index.md
  - Info:
    - "The DiVER's Guide": guide.md
    - Guides: 
      - Test Menu: guide/test-menu.md
      - Replacing LED Boards: guide/led-replace.md
      - DIY LED Boards:      guide/led-pcb.md
      - ALLS Drive Imaging: guide/alls-image.md
      - Custom LED Driver: guide/custom-led-driver.md
      - Networking Guide: guide/router.md
      - Accessory Guide: guide/accessories.md
      - Custom Charts:  guide/custom-charts.md
    - Specifications:
      - Hardware: info/hardware.md
      - Manuals: info/manual.md   
    - Tools:
      - WACCA Launcher: launcher.md